apiVersion: v1
kind: Secret
metadata:
  name: external-dns-azure
type: Opaque
data:
  azure.json: |
    eyJ0ZW5hbnRJZCI6IjkyNDE1MTQ3LTJjOGYtNDlkZS04NTQyLWMyNGYxNTFkYzRiYSIsInN1YnNjcmlwdGlvbklkIjoiOTA3Y2RlMzEtZWNjOC00NWM2LWFkYjMtM2M4NjQ1NWM4ODViIiwicmVzb3VyY2VHcm91cCI6InJnLWNvbnF1ZXJwbGF0Zm9ybS1kZXYtMDEiLCJ1c2VXb3JrbG9hZElkZW50aXR5RXh0ZW5zaW9uIjp0cnVlfQ==
